<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$config['music_genres'] = [

'love' => ['label' => 'Love'],
'romantic' => ['label' => 'Romantic'],
'sad' => ['label' => 'Sad'],
'emotional' => ['label' => 'Emotional'],
'heartbreak' => ['label' => 'Heartbreak'],
'happy' => ['label' => 'Happy'],
'joyful' => ['label' => 'Joyful'],
'chill' => ['label' => 'Chill'],
'relaxing' => ['label' => 'Relaxing'],
'calm' => ['label' => 'Calm'],
'peaceful' => ['label' => 'Peaceful'],
'angry' => ['label' => 'Angry'],
'dark' => ['label' => 'Dark'],
'dramatic' => ['label' => 'Dramatic'],
'hopeful' => ['label' => 'Hopeful'],
'inspirational' => ['label' => 'Inspirational'],
'motivational' => ['label' => 'Motivational'],
'uplifting' => ['label' => 'Uplifting'],
'energetic' => ['label' => 'Energetic'],
'party' => ['label' => 'Party'],
'celebration' => ['label' => 'Celebration'],

// Music Genres
'pop' => ['label' => 'Pop'],
'rock' => ['label' => 'Rock'],
'hiphop' => ['label' => 'Hip-Hop'],
'rap' => ['label' => 'Rap'],
'edm' => ['label' => 'EDM'],
'electronic' => ['label' => 'Electronic'],
'house' => ['label' => 'House'],
'techno' => ['label' => 'Techno'],
'trance' => ['label' => 'Trance'],
'dubstep' => ['label' => 'Dubstep'],
'drum_bass' => ['label' => 'Drum & Bass'],
'jazz' => ['label' => 'Jazz'],
'blues' => ['label' => 'Blues'],
'classical' => ['label' => 'Classical'],
'country' => ['label' => 'Country'],
'folk' => ['label' => 'Folk'],
'indie' => ['label' => 'Indie'],
'alternative' => ['label' => 'Alternative'],
'metal' => ['label' => 'Metal'],
'punk' => ['label' => 'Punk'],
'reggae' => ['label' => 'Reggae'],
'latin' => ['label' => 'Latin'],
'afrobeats' => ['label' => 'Afrobeats'],
'kpop' => ['label' => 'K-Pop'],
'jpop' => ['label' => 'J-Pop'],
'bollywood' => ['label' => 'Bollywood'],
'soul' => ['label' => 'Soul'],
'funk' => ['label' => 'Funk'],
'disco' => ['label' => 'Disco'],

// Music Style
'instrumental' => ['label' => 'Instrumental'],
'acoustic' => ['label' => 'Acoustic'],
'beat' => ['label' => 'Beat'],
'lofi' => ['label' => 'Lo-Fi'],
'remix' => ['label' => 'Remix'],
'cover' => ['label' => 'Cover'],
'orchestra' => ['label' => 'Orchestra'],
'piano' => ['label' => 'Piano'],
'guitar' => ['label' => 'Guitar'],
'vocal' => ['label' => 'Vocal'],
'acappella' => ['label' => 'A Cappella'],
'ambient' => ['label' => 'Ambient'],
'experimental' => ['label' => 'Experimental'],

// Media
'soundtrack' => ['label' => 'Soundtrack'],
'background_music' => ['label' => 'Background Music'],
'film_score' => ['label' => 'Film Score'],
'trailer_music' => ['label' => 'Trailer Music'],
'cinematic' => ['label' => 'Cinematic'],
'game_music' => ['label' => 'Game Music'],
'podcast_intro' => ['label' => 'Podcast Intro'],
'advertisement' => ['label' => 'Advertisement'],
'corporate' => ['label' => 'Corporate'],

// Wellness
'meditation' => ['label' => 'Meditation'],
'yoga' => ['label' => 'Yoga'],
'sleep' => ['label' => 'Sleep'],

// Religious / Spiritual
'documentary' => ['label' => 'Documentary'],
'prayer' => ['label' => 'Prayer'],
'devotional' => ['label' => 'Devotional'],
'bhajan' => ['label' => 'Bhajan'],
'kirtan' => ['label' => 'Kirtan'],
'chant' => ['label' => 'Chant'],
'spiritual' => ['label' => 'Spiritual'],
'worship' => ['label' => 'Worship'],

// Kids
'kids' => ['label' => 'Kids'],
'nursery_rhymes' => ['label' => 'Nursery Rhymes'],
'educational' => ['label' => 'Educational'],
'storytelling' => ['label' => 'Storytelling'],

];